spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.114.131
    port: 5672
    username: admin
    password: 123456
  sleuth:
    sampler:
      probability: 0.1
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
    
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
    #配置路由， 可以不配置，默认就可以转发
    #整合ribbon重试 默认false
  retryable: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
#降低超时时间，方便测试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream